-- select * from order_details;
SELECT * FROM EMPLOYEES;
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;
SELECT * FROM CATEGORIES;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDER_DETAILS;
SELECT * FROM SHIPPERS;
SELECT * FROM SUPPLIERS;

select * from giocatori;
SELECT * FROM ZS_UTENTI;